### ISSUE TITLE
Standard fields are missing in Options

### ISSUE THREAD

**Issue by thejulian** [eyp/redmine_spent_time#101]
I can't select the standard fields in the sections "avaible columns". 
I need the column "_Estimated Time_". Am I missing something or doesn't the plugin support the standard fields?

[Click here for a screenshot -> IMGUR](http://imgur.com/ZfozQRI)

**Comment by eyp** [comment]
I'm sorry, that's not my plugin, I think that's part of the standard Redmine installation.
