### ISSUE TITLE
Display spent time using the new Redmine 3.4 format HH:MM

### ISSUE THREAD

**Issue by Atmis** [eyp/redmine_spent_time#104]
Hi,

Would it be possible to update the plugin to follow the new setting in Redmine that displays the time entries in the HH:MM format instead of decimals ? This way the Spent Time plugin would be consistent with the rest of the system.

Thank a lot for your plugin anyway

Pierre

**Comment by Atmis** [comment]
Here is the link to the Feature on Redmine website :
http://www.redmine.org/issues/23996

**Comment by eyp** [comment]
Yes, of course. I'm having a look at the link you sent. I'll try to make the change ASAP.

**Comment by eyp** [comment]
Done

**Comment by Atmis** [comment]
Update applied, works great, thank you !
