### ISSUE TITLE
notifications

### ISSUE THREAD

**Issue by mmiat** [eyp/redmine_spent_time#106]
i'd like that other project members or project owner will be notified when someone add a time spent record

**Comment by eyp** [comment]
That functionality should be developed in the main core of Redmine, I don't think that's a work for my plugin, because what happens if the user logs the work time within the Issue instead of using the plugin?.

**Comment by mmiat** [comment]
yes, you right, but i don't think it will be developed in the main core :(

**Comment by eyp** [comment]
TBH, notifications are annoying everywhere. What's the point of being notified if someone logs work hours in an issue?. You could just run a report of spent time in a project then see who logged time. 

But notifications are usually forgotten, filtered or simply thrown to the bin. That's what I've seen in every place I've worked at. IMO, a notification should be sent only for very important things, I think.

**Comment by mmiat** [comment]
for customers. when I create a project, the customer buy X hours of support, so he wants to know when and how many hours are used/consumed.

**Comment by eyp** [comment]
Then you should send them a report. If you send notifications every time someone (or you) logs time, your client will have to add the amounts of time, make a calendar or whatever (make a report in the end). I think the report could be done within the project's SpentTime (core functionality).

On the other hand I was thinking on developing report with more filters within my plugin, and the possibility to download a PDF with the results.

The part of the filters is almost done (not commited yet), but I haven't done anything about the PDF part.
