### ISSUE TITLE
Undefined method format_hours

### ISSUE THREAD

**Issue by alegros53** [eyp/redmine_spent_time#107]
Hi, I've got en issues after updating this module.
In my logfile 

ActionView::Template::Error (undefined method `format_hours' for #<#<Class:0x007fe4f455db98>:0x007fe4fbbd2fd0>):
    1: <div id="time_entries_report">
    2:   <div class="total-hours">
    3:     <p><%= t(:label_total_time) %> <%= format_hours(@entries.sum(:hours).to_f) %> <%= l(:field_hours) %> / <span style="font-weight: normal;"><%= t(:label_total_estimated_time) %> <%= format_hours(@total_estimated_time) %> <%= l(:field_hours) %></span></p>
    4:   </div>
    5:
    6:   <table class="list time-entries">
  plugins/redmine_spent_time/app/views/spent_time/_time_entries_report.html.erb:3:in `_plugins_redmine_spent_time_app_views_spent_time__time_entries_report_html_erb__3343373034121870399_70310663132540'
  plugins/redmine_spent_time/app/views/spent_time/index.html.erb:30:in `_plugins_redmine_spent_time_app_views_spent_time_index_html_erb___2434290802448193975_70310664231700'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

Do you have any idea ?

**Comment by eyp** [comment]
What version of Redmine are you using?

**Comment by alegros53** [comment]
Sorry, i forgot it

Environment:
  Redmine version                3.2.0.stable.15058
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux-gnu]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2

**Comment by eyp** [comment]
Unfortunately last updates have broken the compaibility with Redmine versions prior to 3.4
This issue has broken that compatibility... https://github.com/eyp/redmine_spent_time/issues/104
The README file is not updated with last issues because I was expecting to finish another issue faster, but it's been delayed. You must downgrade the plugin to the last release gfound in the releases page, or upgrade Redmine to >=  3.4

**Comment by eyp** [comment]
I think is not bad idea to upgrade Readmine to last version since it's not needed to upgrade Rails either Ruby

**Comment by alegros53** [comment]
Ok so how to downgrade this plugins ?

**Comment by eyp** [comment]
Just go to https://github.com/eyp/redmine_spent_time/releases page, download the zip file and decompress it in the plugins folder

**Comment by eyp** [comment]
It's not needed anymore since the database was not modified

**Comment by eyp** [comment]
Another option is to have the last update from the repository, then overwrite these 3 files... so you have the rest of updates but the last one that is which is breaking everything:

https://github.com/eyp/redmine_spent_time/blob/bf9d54bb819fac47823d3484a7ebb205f9537139/app/views/spent_time/_time_entries_by_date.html.erb
https://github.com/eyp/redmine_spent_time/blob/bf9d54bb819fac47823d3484a7ebb205f9537139/app/views/spent_time/_time_entries_report.html.erb
https://github.com/eyp/redmine_spent_time/blob/bf9d54bb819fac47823d3484a7ebb205f9537139/app/views/spent_time/_time_entry_row.html.erb

**Comment by alegros53** [comment]
Ok thanks. I've downgrade the plugin, i will upgrade redmine to 3.4 when i will get time to do it :-) 

Thanks for your quick reply.

**Comment by eyp** [comment]
Sorry, I think I'm messing or complicating the things.... Or just download the plugin repo previous to that commit:

https://github.com/eyp/redmine_spent_time/tree/8a1f56c9233f775d77039a11da132514ef43baa9
