### ISSUE TITLE
Redmine 4.x support

### ISSUE THREAD

**Issue by camlafit** [eyp/redmine_spent_time#114]
Hello

Do you plan to update this very nice plugin to redmine 4.x

Thanks

**Comment by eyp** [comment]
Hello, I thought it was not used anymore, but if there's someone
interested, why not? sure!

**Comment by eyp** [comment]
Is there any problem running it on Redmine 4.x?, I've just installed it and it works. My environment is Ruby 2.5.5, Rails 5.2.3 and Redmine 4.0.4.
