### ISSUE TITLE
redmine 3.0

### ISSUE THREAD

**Issue by dfreudenberger** [eyp/redmine_spent_time#68]
any plans on updating it to redmine 3.0?

**Comment by eyp** [comment]
Just realized there is a Redmine 3 version, LOL.... Yes, I'll update the plugin.

**Comment by dfreudenberger** [comment]
very cool, thank you

**Comment by artacademy** [comment]
Hi,

does anyone experience performance issues with Redmine version 3.0.1.?
Querying "all spent time over all projects" (which is a base task in Redmine) results in temporary data >1GB which we cannot efford to handle on our Redmine VM.

I can give more details / data to the issue we are experiencing but first I just wanted to find out whether or not I am alone with the issue :)

Thanking you 

artacademy

**Comment by eyp** [comment]
Just released a new version 3.0.0 that works with Redmine 3.0, Rails 4.2 & Ruby 2.2.1
I've had to remove the feature of editing inline the times because best_in_place plugin doesn't work fine now :(

**Comment by dfreudenberger** [comment]
@eyp thank you very much :)
