### ISSUE TITLE
add link to your site

### ISSUE THREAD

**Issue by mmiat** [eyp/redmine_spent_time#71]
in administration > plugins link to your site / github repository is missing

**Comment by eyp** [comment]
Sorry, don't find how to do it within the init.rb file, any idea?

**Comment by mmiat** [comment]
I'm not a ruby developer, but checking other plugins I've found this:
author_url 'https://github.com/eyp/redmine_spent_time'
bye




----Messaggio originale----

Da: notifications@github.com

Data: 20/04/2015 11.01

A: "eyp/redmine_spent_time"<redmine_spent_time@noreply.github.com>

Cc: "mmiat"<mmiat@libero.it>

Ogg: Re: [redmine_spent_time] add link to your site (#71)




Sorry, don't find how to do it within the init.rb file, any idea?

**Comment by eyp** [comment]
Thanks, just added project URL and author URL.
