### ISSUE TITLE
Closed projects are not included in report

### ISSUE THREAD

**Issue by adressler** [eyp/redmine_spent_time#73]
Hello,
thank you for this great plugin.
We use plugin version 2.6.6 in Redmine 2.5.2, Ruby 2.0.0, Rails 3.2.19
I expect the report to show all of my spent time for a given period. If a project is closed, the time of this project is not included in the report, giving me less hours spent in the same time period.
Is there a reason why only active projects are included in the report?

**Comment by Yumash** [comment]
+1

**Comment by eyp** [comment]
Fixed in 2.6.7
