### ISSUE TITLE
Time displays 0.00 when time entry is not linked to an issue

### ISSUE THREAD

**Issue by Atmis** [eyp/redmine_spent_time#74]
Hi,

We noticed that when displaying the report, entries that are related to a project, but not an issue, are diplaying 0.00 instead of the value recorded. On the other hand, the total for the day is correct. See pic below.

![screenshot 2015-06-22 20_02_17 pma](https://cloud.githubusercontent.com/assets/5329747/8288977/db35db54-1919-11e5-885a-e741046307bd.png)

Using current version of Redmine Spent Time with Redmine 3.0.3.

Pierre

**Comment by eyp** [comment]
Ok, I'll take a look when possible. Currently I'm very busy with personal life... just moved to a new country.

**Comment by Atmis** [comment]
Wow, that's not everyday that someone moves to a new country ! Happy moving.

To be more specific about our current setup, we are using Redmine trunk from sunday evening (21/06/2015). I deactivated the Time Spent plugin until further investigation :

Environment:
  Redmine version                3.0.3.devel
  Ruby version                   2.0.0-p645 (2015-04-13) [x64-mingw32]
  Rails version                  4.2.2
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Git                            1.9.5
  Filesystem                     
Redmine plugins:
  clipboard_image_paste          1.10
  redmine_checklists             3.1.1
  redmine_contacts               4.0.1
  redmine_csv_with_bom           0.0.2
  redmine_dmsf                   1.5.2 devel
  redmine_inline_note_images_plugin 0.0.1
  redmine_landing_page           0.1.0
  redmine_last_updated_by_column 0.3.0
  redmine_lightbox2              0.2.2
  redmine_local_avatars          0.2.0
  redmine_mail_handler_clean_body_regexp 0.1
  redmine_my_page_queries        2.1.6
  redmine_silencer               0.4.0
  redmine_stealth                0.6.0
  sidebar_hide                   0.0.7
