### ISSUE TITLE
Incomplete issues list in combo box

### ISSUE THREAD

**Issue by R-i-c-k-y** [eyp/redmine_spent_time#75]
Hi EYP

I migrated from redmine 2.5.0 with your plugin in version 2.6.3 (perfectly working) to redmine 3.0.4 and plugin in 3.0.2 version.

I noticed that now, when I select a project with various issues assigned to me, I don'see them all in issue combo box. Here an example of the difference:

...the new one....
![image](https://cloud.githubusercontent.com/assets/432347/8799242/f8a23dc2-2fa8-11e5-9297-e621cfcb50fe.png)

....the old one.... (the database is exactly the same)
![image](https://cloud.githubusercontent.com/assets/432347/8799268/2cc19fd0-2fa9-11e5-8dfd-ae596e68e2c4.png)

Any hint?
Thanks for your great work!

**Comment by eyp** [comment]
Are the issues closed?

**Comment by R-i-c-k-y** [comment]
no.... I just tried to show you the difference between new and old installation... I'm still in this situation

**Comment by eyp** [comment]
I'm sorry, but I'm trying to install Ruby on Windows at my new work without success :(. I've always worked on Linux or OSX and did't have any problems... And also I've moved to a new country and still don't have internet connection at home, so I'll keep on trying to get everything installed, but for now all the issues will have to wait.

Sorry.

**Comment by DiegoFraser** [comment]
I can speak in favor of Bitnami Ruby Stack for Windows (https://bitnami.com/stack/ruby/installer). I’m a total newbie to Ruby on Rails and it made the installation process totally painless. I hope you find this recommendation useful.

Good luck!

De: Eduardo Yáñez Parareda [mailto:notifications@github.com]
Enviado el: jueves, 23 de julio de 2015 12:03
Para: eyp/redmine_spent_time <redmine_spent_time@noreply.github.com>
Asunto: Re: [redmine_spent_time] Incomplete issues list in combo box (#75)


I'm sorry, but I'm trying to install Ruby on Windows at my new work without success :(. I've always worked on Linux or OSX and did't have any problems... And also I've moved to a new country and still don't have internet connection at home, so I'll keep on trying to get everything installed, but for now all the issues will have to wait.

Sorry.

**Comment by eyp** [comment]
The problem with Bitnami RS is that I don't have administration permissions, so I can't use it. I need something like the http://rubyinstaller.org/ but I haven't get it working right.

**Comment by R-i-c-k-y** [comment]
OK, I'll wait for you.
Meanwhile, I'll search a solution on my own

Bye
