### ISSUE TITLE
Version 3.1.2 does not contain all the changes for pull request #77

### ISSUE THREAD

**Issue by TobiasZip** [eyp/redmine_spent_time#79]
It seems the fix to get all projects in spent_time_controler.rb is missing in version 3.1.2.

When I download the zip archive and check the file at line 41 Project.find(:all) is still used.

**Comment by eyp** [comment]
Thx, I'll revise it

**Comment by eyp** [comment]
I guess I made the tag befire the merge, because I don't find another explanation. It's fixed now. Thank you!

**Comment by TobiasZip** [comment]
Just tested it, everything is fine now. Thanks!
