### ISSUE TITLE
Problem to select project in combobox

### ISSUE THREAD

**Issue by pchovanak** [eyp/redmine_spent_time#82]
Hello, 
there are no project and issues to select when I am doing new entry.Can you help me?

Redmine: 3.1.1
Spent TIme: 3.1.2

**Comment by eyp** [comment]
Are you a member of any project and assigned to any issue?

**Comment by pchovanak** [comment]
I am sorry, I was sure that I am member, but was using admin login, so... Everything seems OK now.
Thanks for your quick suport.

**Comment by eyp** [comment]
No problem!
