### ISSUE TITLE
Filter Hours is none returns no results

### ISSUE THREAD

**Issue by gboul** [eyp/redmine_spent_time#86]
I am trying to list the users that spent no time on any project. I set the Hour filter to none and the date to a period of time, I was expecting to find users that have logged no time during that period.
But I got no results.

When I tried to set the hour filter to less than, it ignored the date filter.

Is it possible to list the users that have no logged time, using the spent time plugin?

**Comment by eyp** [comment]
I think you can do that form the own Redmine's spent time report. Project->Overview->right side (Spent time) -> Report. There you have more powerful filters...
