### ISSUE TITLE
translation missing: fr.label_la_admin

### ISSUE THREAD

**Issue by NK74** [eyp/redmine_spent_time#95]
Menu button : translation missing: fr.label_la_admin :+1: 

And when i press 404 ERROR ...

**## Environment:**
  Redmine version             3.2.3.stable
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux-gnu]
  Rails version                   4.2.5.2
  Environment                   production
  Database adapter          Mysql2

redmine_spent_time        3.1.2

**Comment by eyp** [comment]
Cannot reproduce in Redmine 4.0.4.
