### ISSUE TITLE
Chrome do not show "calendar" on "spent time" page

### ISSUE THREAD

**Issue by IlyaRa72** [eyp/redmine_spent_time#98]
Hi!
I use the "spent time" plugin for redmine v 3.3 and, it's working very good.
But, it has some bugs with "drawing" - when I use mozilla firefox the main spent time page showing correctly - i.e. "calendar" picture near by date input field, but, when I use  chrome, this page NOT show this calendar picture :(
![2016-12-16 10 18 04](https://cloud.githubusercontent.com/assets/24602318/21254880/882c0c9c-c379-11e6-942a-035518483821.png)
![2016-12-16 10 18 12](https://cloud.githubusercontent.com/assets/24602318/21254881/8834af00-c379-11e6-82a2-7057a2c7d35a.png)

**Comment by eyp** [comment]
Thank you for the remark!. However as a workaround you can still type the date manually, can't you?

**Comment by IlyaRa72** [comment]
yes, manually it's possible

**Comment by eyp** [comment]
Ok, good to know. Thank you!

**Comment by IlyaRa72** [comment]
Thanks!

**Comment by vpistis** [comment]
I think it's simply possible to change the `type` attribute of `input` tags from `text` to `date`, without using `datepicker`, now browsers supports natively the attribute `type="date"`.

**Comment by eyp** [comment]
Ok, I'll try to change it and see if it works properly on both browsers (FF & CH)

**Comment by vpistis** [comment]
I noted now that firefox and IE doesn't support the `type="date"`, but Chrome yes :)
I think is possible to add the `type="date"` that is correctly used by chrome based browsers. Firefox can use `datepicker` that runs correctly.
Obviously the UI of the input tag is not the same when use `type="date"`.

**Comment by TobiasZip** [comment]
We could fix this by changing the the `text_field_tag` for 'from' and 'to' to `date_field_tag` in _index.html.erb_

**Comment by eyp** [comment]
Changes date fields to date_tag_fields
